services:

  web:
    image: finfilo-service:latest
    ports:
      - "8080:8080"
    working_dir: /app
    command: python3 /app/run_app.py
    environment:
      DATABASE_CONN_STR: mysql+pymysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - redis
    restart: always

  web_slave:
    image: finfilo-service:latest
    ports:
      - "8081:8080"
    working_dir: /app
    command: python3 /app/run_app.py
    environment:
      DATABASE_CONN_STR: mysql+pymysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - redis
    restart: always

  scheduler:
    image: finfilo-service:latest
    working_dir: /app
    command: python3 /app/job_server.py
    environment:
      DATABASE_CONN_STR: mysql+pymysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - redis
    restart: always

  job_server:
    image: finfilo-service:latest
    working_dir: /app
    command: python3 /app/job_server_mq.py
    environment:
      DATABASE_CONN_STR: mysql+pymysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - db
      - redis
    restart: always

  job_server_slave:
    image: finfilo-service:latest
    working_dir: /app
    command: python3 /app/job_server_mq.py
    environment:
      DATABASE_CONN_STR: mysql+pymysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - redis
    restart: always

  news_server:
    image: finfilo-service:latest
    working_dir: /app
    command: python3 /app/news_server.py
    environment:
      DATABASE_CONN_STR: mysql+pymysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - redis
    restart: always

  redis:
    image: registry.openanolis.cn/openanolis/redis:5.0.3-8.6
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--protected-mode", "no"]
    volumes:
      - /mnt/redis-data:/data
    restart: always

  db:
    image: registry.openanolis.cn/openanolis/mysql:8.0.30-8.6
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
        - /mnt/mysql-data:/var/lib/mysql
        # 可选：挂载自定义配置（更清晰）
        # - ./mysql/conf.d:/etc/mysql/conf.d
    command: >
        --bind-address=0.0.0.0
        --default-time-zone='+08:00'
        --sql-mode=""
        --innodb-buffer-pool-size=8G
        --innodb-log-file-size=512M
        --innodb-flush-log-at-trx-commit=2
        --innodb-write-io-threads=16
        --innodb-read-io-threads=16
        --sync-binlog=0
        --max-connections=200
        --table-open-cache=2000
        --open-files-limit=4096
        --skip-name-resolve
        --disable-log-bin
    restart: always
